### ISSUE TITLE
can u let me know picom useflags?

### ISSUE THREAD

**Issue by evilja** [lepz0r/tilingwm-rices#1]
![Screenshot at 2022-03-03 18-42-57](https://user-images.githubusercontent.com/97121235/156631255-5a317b6c-84ff-4fcd-bef9-64af8fbceceb.png)

**Comment by lepz0r** [comment]
use picom 9.1 instead of picom 8.2
my use flags: `config-file dbus doc drm opengl pcre -test`

**Comment by evilja** [comment]
Thx

5 Mar 2022 Cmt 02:06 tarihinde Ryan Putrama Yahya ***@***.***>
şunu yazdı:
