### ISSUE TITLE
[Super noob question] Why does waybar expand the way it does when it's only one application open in the workspace?

### ISSUE THREAD

**Issue by imli700** [lepz0r/tilingwm-rices#3]
More than one application: 
![image](https://user-images.githubusercontent.com/76049491/192079444-09e61d0b-02b2-4c3c-b000-7674acd19349.png)

Only one application:
![image](https://user-images.githubusercontent.com/76049491/192079475-6014b0ac-111d-47fc-bc10-a8561c37535e.png)

**Comment by lepz0r** [comment]
can you show me your sway config here?

**Comment by imli700** [comment]
Sure:

`#######################
### STYLE SETTINGS ####
#######################

# style
default_border 		        pixel 	1
titlebar_border_thickness 		1
gaps 			            top	    	10
gaps 			            bottom	0
gaps 			            left	5
gaps 			            right	5
gaps 			            inner 	10

# window decorations
# class			        border	    background	text        indicator   child_border
client.focused          #80a0ff     #303030     #c6c6c6     #80a0ff     #80a0ff
client.focused_inactive #80a0ff     #303030     #c6c6c6     #80a0ff     #80a0ff
client.unfocused        #80a0ff     #080808     #c6c6c6     #80a0ff     #303030
client.urgent           #80a0ff     #80a0ff     #080808     #80a0ff     #80a0ff


# Default config for sway
#
# Copy this to ~/.config/sway/config and edit it to your liking.
#
# Read `man 5 sway` for a complete reference.

### Variables
#
# Logo key. Use Mod1 for Alt.
set $mod Mod4
# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l
# Your preferred terminal emulator
set $term foot
# Your preferred application launcher
# Note: pass the final command to swaymsg so that the resulting window can be opened
# on the original workspace that the command was run on.
#default: set $menu dmenu_path | dmenu | xargs swaymsg exec --
set $menu "rofi -show run"

### Output configuration
#
#
# Example configuration:
#
#   output HDMI-A-1 resolution 1920x1080 position 1920,0
#
# You can get the names of your outputs by running: swaymsg -t get_outputs

### Idle configuration
#
# Example configuration:
#
# exec swayidle -w \
#          timeout 300 'swaylock -f -c 000000' \
#          timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
#          before-sleep 'swaylock -f -c 000000'
#
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.

### Input configuration
#
# Example configuration:
#
#   input "2:14:SynPS/2_Synaptics_TouchPad" {
#       dwt enabled
#       tap enabled
#       natural_scroll enabled
#       middle_emulation enabled
#   }
#
# You can get the names of your inputs by running: swaymsg -t get_inputs
# Read `man 5 sway-input` for more information about this section.

### Key bindings
#
# Basics:
#
    # Start a terminal
    bindsym $mod+Return exec $term

    # Kill focused window
    bindsym $mod+Shift+q kill

    # Start your launcher
    bindsym $mod+d exec $menu

    # Drag floating windows by holding down $mod and left mouse button.
    # Resize them with right mouse button + $mod.
    # Despite the name, also works for non-floating windows.
    # Change normal to inverse to use left mouse button for resizing and right
    # mouse button for dragging.
    floating_modifier $mod normal

    # Reload the configuration file
    bindsym $mod+Shift+c reload
#
# Moving around:
#
    # Move your focus around
    bindsym $mod+$left focus left
    bindsym $mod+$down focus down
    bindsym $mod+$up focus up
    bindsym $mod+$right focus right
    # Or use $mod+[up|down|left|right]
    bindsym $mod+Left focus left
    bindsym $mod+Down focus down
    bindsym $mod+Up focus up
    bindsym $mod+Right focus right

    # Move the focused window with the same, but add Shift
    bindsym $mod+Shift+$left move left
    bindsym $mod+Shift+$down move down
    bindsym $mod+Shift+$up move up
    bindsym $mod+Shift+$right move right
    # Ditto, with arrow keys
    bindsym $mod+Shift+Left move left
    bindsym $mod+Shift+Down move down
    bindsym $mod+Shift+Up move up
    bindsym $mod+Shift+Right move right
#
# Workspaces:
#
    # Switch to workspace
    bindsym $mod+1 workspace number 1
    bindsym $mod+2 workspace number 2
    bindsym $mod+3 workspace number 3
    bindsym $mod+4 workspace number 4
    bindsym $mod+5 workspace number 5
    bindsym $mod+6 workspace number 6
    bindsym $mod+7 workspace number 7
    bindsym $mod+8 workspace number 8
    bindsym $mod+9 workspace number 9
    bindsym $mod+0 workspace number 10
    # Move focused container to workspace
    bindsym $mod+Shift+1 move container to workspace number 1
    bindsym $mod+Shift+2 move container to workspace number 2
    bindsym $mod+Shift+3 move container to workspace number 3
    bindsym $mod+Shift+4 move container to workspace number 4
    bindsym $mod+Shift+5 move container to workspace number 5
    bindsym $mod+Shift+6 move container to workspace number 6
    bindsym $mod+Shift+7 move container to workspace number 7
    bindsym $mod+Shift+8 move container to workspace number 8
    bindsym $mod+Shift+9 move container to workspace number 9
    bindsym $mod+Shift+0 move container to workspace number 10
    # Note: workspaces can have any name you want, not just numbers.
    # We just use 1-10 as the default.
#
# Layout stuff:
#
    # You can "split" the current object of your focus with
    # $mod+b or $mod+v, for horizontal and vertical splits
    # respectively.
    bindsym $mod+b splith
    bindsym $mod+v splitv

    # Switch the current container between different layout styles
    bindsym $mod+s layout stacking
    bindsym $mod+w layout tabbed
    bindsym $mod+e layout toggle split

    # Make the current focus fullscreen
    bindsym $mod+f fullscreen

    # Toggle the current focus between tiling and floating mode
    bindsym $mod+Shift+space floating toggle

    # Swap focus between the tiling area and the floating area
    bindsym $mod+space focus mode_toggle

    # Move focus to the parent container
    bindsym $mod+a focus parent
#
# Scratchpad:
#
    # Sway has a "scratchpad", which is a bag of holding for windows.
    # You can send windows there and get them back later.

    # Move the currently focused window to the scratchpad
    bindsym $mod+Shift+minus move scratchpad

    # Show the next scratchpad window or hide the focused scratchpad window.
    # If there are multiple scratchpad windows, this command cycles through them.
    bindsym $mod+minus scratchpad show
#
# Resizing containers:
#
mode "resize" {
    # left will shrink the containers width
    # right will grow the containers width
    # up will shrink the containers height
    # down will grow the containers height
    bindsym $left resize shrink width 10px
    bindsym $down resize grow height 10px
    bindsym $up resize shrink height 10px
    bindsym $right resize grow width 10px

    # Ditto, with arrow keys
    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px

    # Return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+r mode "resize"

include /etc/sway/config.d/*

#######################
### CUSTOM SETTINGS ###
#######################

#touchpad
input type:touchpad {
tap enabled
natural_scroll enabled
middle_emulation enabled
pointer_accel 0.3 #Changing the pointer speed
}

#sets bar to waybar
bar {
swaybar_command waybar
}

#volume keys
bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%

#Brightness
bindsym XF86MonBrightnessDown exec brightnessctl s 5%-
bindsym XF86MonBrightnessUp exec brightnessctl s +5%

# shutdown / restart / suspend...
set $Locker swaylock -i "~/Pictures/wallpapers/moon.jpg", mode "default" #not really necessary but looks cleaner below
set $mode_system System (l) lock, (e) logout, (s) suspend, (r) reboot, (CTRL+s) shutdown

mode "$mode_system" {
    bindsym l exec --no-startup-id swaylock 
    bindsym e exec --no-startup-id swaymsg exit, mode "default"
    bindsym s exec --no-startup-id systemctl suspend && $Locker
    bindsym r exec --no-startup-id systemctl reboot, mode "default"
    bindsym Ctrl+s exec --no-startup-id systemctl poweroff -i, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+BackSpace mode "$mode_system"

#flameshot. In seperate section becaues this is very complicated
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK
exec hash dbus-update-activation-environment 2>/dev/null && \ dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK
bindsym $mod+Shift+s exec flameshot gui

#wayland gtk settings
exec {
    gsettings set $gnome-schema gtk-theme 'Catppuccin-Mocha'
    gsettings set $gnome-schema icon-theme 'Papirus'
#    gsettings set $gnome-schema cursor-theme 'Your cursor Theme'
#    gsettings set $gnome-schema font-name 'Your font name'
}

#wallpaper
output * bg $HOME/Pictures/wallpapers/lighthouse.jpg fit

#application startup
exec mako
exec sleep 4s && megasync #megasync works properly if opened after a few seconds after startup
exec nm-applet --indicator
exec powerprofilesctl set power-saver
output eDP-1 mode 1920x1080@48.014Hz position 0,0

#system statups
exec pactl set-source-mute @DEFAULT_SOURCE@ toggle # mutes microphone on startup
exec pactl set-sink-volume @DEFAULT_SINK@ 50% #sets volume to 50 on startup
exec pactl set-sink-mute @DEFAULT_SINK@ toggle #mutes volume on startup`

**Comment by imli700** [comment]
Sure: https://github.com/imli700/dotfiles/blob/main/.config/sway/config

**Comment by lepz0r** [comment]
did you delete your dotfiles repo? also enable smart gaps on sway config by using `smart_gaps on`

**Comment by imli700** [comment]
> did you delete your dotfiles repo?

Turns out it was a private repo. changed it to public. Here:  https://github.com/imli700/dotfiles/blob/main/.config/sway/config

> also enable smart gaps on sway config by using `smart_gaps on`

This is what happens after enabling smart gaps:

![image](https://user-images.githubusercontent.com/76049491/192930969-c3889b36-4190-4360-b1dc-df7f637b9deb.png)

Is this the intended result?

**Comment by lepz0r** [comment]
Also enable smart borders with `smart_border no_gaps`

**Comment by imli700** [comment]
done: 
![image](https://user-images.githubusercontent.com/76049491/192932162-fd774bd0-1c2e-45ca-a20f-5462993d5b81.png)
